In [3]:
import numpy as np

In [37]:
# Matriz X (compuerta Pauli-X)
x = np.array([[0, 1], 
              [1, 0]])

# Matriz Y (compuerta Pauli-Y)
y = np.array([[0, -1j], 
              [1j, 0]])

# Matriz Z (compuerta Pauli-Z)
z = np.array([[1, 0], 
              [0, -1]])

# Matriz Hadamar
h = 1/np.sqrt(2)*np.array([[1,1],
                           [1,-1]]) 

# Matriz I (compuerta Pauli-Z)
i = np.array([[1, 0], 
              [0, 1]])

t = np.array([[1, 0], 
              [0, np.pi/4]])

print("Compuerta X")
print(x)
print("Compuerta Y")
print(y)
print("Compuerta Z")
print(z)
print("Compuerta H")
print(h)
print("Compuerta I")
print(i)
print("Compuerta T")
print(t)

Compuerta X
[[0 1]
 [1 0]]
Compuerta Y
[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
Compuerta Z
[[ 1  0]
 [ 0 -1]]
Compuerta H
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
Compuerta I
[[1 0]
 [0 1]]
Compuerta T
[[1.         0.        ]
 [0.         0.78539816]]


In [5]:
q0 = np.array([[np.sqrt(3)/2],
               [1/2]])

print(q0)

[[0.8660254]
 [0.5      ]]


In [6]:
# Se multiplica primero la compuerta y despúes el estado
s1 = np.dot(x,q0)
print(s1)

[[0.5      ]
 [0.8660254]]


In [7]:
s2 = np.dot(y, s1)*(1/1j)
print(s2)

[[-0.8660254-0.j]
 [ 0.5      +0.j]]


In [8]:
s3 = np.dot(z, s2)
print(s3)

[[-0.8660254+0.j]
 [-0.5      +0.j]]


In [9]:
s3 = np.dot(z, s2)*-1
print(s3)

[[0.8660254-0.j]
 [0.5      -0.j]]


In [10]:
s4 = np.dot(h, s3)
print(s4)

[[0.96592583+0.j]
 [0.25881905+0.j]]


In [11]:
multiplicacion = np.dot(x,h)
print(multiplicacion)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [12]:
multiplicacion = np.dot(h,x)
print(multiplicacion)

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [15]:
q0 = np.array([[0,1],
               [1,0]])

print(q0)

[[0 1]
 [1 0]]


In [16]:
negacion = np.dot(q0,x)
print(negacion)

[[1 0]
 [0 1]]


In [19]:
q1 = np.array([[1,0],
               [0,1]])

print(q1)

[[1 0]
 [0 1]]


In [18]:
negacion_1 = np.dot(q1,x)
print(negacion_1)

[[0 1]
 [1 0]]


In [26]:
q2 = np.array([[np.sqrt(3)/2, 1/2]])
print(q2)

[[0.8660254 0.5      ]]


In [27]:
negacion_2 = np.dot(q2,x)
print(negacion_2)

[[0.5       0.8660254]]


In [28]:
q3 = np.array([[1/2,np.sqrt(3)/2]])
print(q3)

[[0.5       0.8660254]]


In [29]:
negacion_3 = np.dot(q3,x)
print(negacion_3)

[[0.8660254 0.5      ]]


In [32]:
q1 = np.array([[1,0],
               [0,1]])

print("q1")
print(q1)

q2 = np.dot(q1,x)
q3 = np.dot(q2,x)

print("q2")
print(q2)
print("q3")
print(q3)

q1
[[1 0]
 [0 1]]
q2
[[0 1]
 [1 0]]
q3
[[1 0]
 [0 1]]


In [33]:
q1 = np.array([[1,0],
               [0,1]])

print("q1")
print(q1)

q2 = np.dot(q1,x)
q3 = np.dot(q2,x)
q4 = np.dot(q3,x)

print("q2")
print(q2)
print("q3")
print(q3)
print("q4")
print(q4)

q1
[[1 0]
 [0 1]]
q2
[[0 1]
 [1 0]]
q3
[[1 0]
 [0 1]]
q4
[[0 1]
 [1 0]]


In [39]:
q1 = np.array([[1,0],
               [0,1]])

print("q1")
print(q1)

q2 = np.dot(q1,x)
q3 = np.dot(q2,z)

print("q2")
print(q2)
print("q3")
print(q3)

q1
[[1 0]
 [0 1]]
q2
[[0 1]
 [1 0]]
q3
[[ 0 -1]
 [ 1  0]]


In [38]:
q1 = np.array([[1,0],
               [0,1]])

print("q1")
print(q1)

q2 = np.dot(q1,t)

print("q2")
print(q2)

q1
[[1 0]
 [0 1]]
q2
[[1.         0.        ]
 [0.         0.78539816]]


In [40]:
q1 = np.array([[1,0],
               [1,0]])

print(q1)

[[1 0]
 [1 0]]
