In [110]:
import qiskit
import qiskit_aer
print(qiskit_aer.__version__)
print(qiskit.__version__)
import numpy as np

0.15.0
1.1.1


In [134]:
# Matriz X (compuerta Pauli-X)
x = np.array([[0, 1], 
              [1, 0]])

# Matriz Y (compuerta Pauli-Y)
y = np.array([[0, -1j], 
              [1j, 0]])

# Matriz Z (compuerta Pauli-Z)
z = np.array([[1, 0], 
              [0, -1]])

# Matriz Hadamar
h = 1/np.sqrt(2)*np.array([[1,1],
                           [1,-1]]) 

# Matriz I (compuerta Pauli-Z)
i = np.array([[1, 0], 
              [0, 1]])

# Matriz SWAP 
swap = np.array([[1, 0, 0, 0], 
                 [0, 0, 1, 0], 
                 [0, 1, 0, 0], 
                 [0, 0, 0, 1],],)

# Matriz CNOT 
cnot = np.array([[1, 0, 0, 0], 
                 [0, 1, 0, 0], 
                 [0, 0, 0, 1], 
                 [0, 0, 1, 0],],)

print("Matriz X")
print(x)
print('')
print("Matriz Y")
print(y)
print('')
print("Matriz Z")
print(z)
print('')
print("Matriz H")
print(h)
print('')
print("Matriz I")
print(i)
print('')

Matriz X
[[0 1]
 [1 0]]

Matriz Y
[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]

Matriz Z
[[ 1  0]
 [ 0 -1]]

Matriz H
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

Matriz I
[[1 0]
 [0 1]]



In [135]:
print("Matriz SWAP")
print(swap)
print('')
print("Matriz CNOT")
print(cnot)

Matriz SWAP
[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]

Matriz CNOT
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [132]:
# Qbit 0 con estado 0
print('Qbit 0 con estado 0 = 1(0) 0(1)')
q0 = np.array([[1],
               [0]])
print(q0)
print('')

# Qbit 1 con estado 1
print('Qbit 1 con estado 1 = 0(0) 1(0)')
q1 = np.array([[0],
               [1]])
print(q1)
print('')

# Producto tensorial de q0 y q0
print('')
print('Producto tensorial de 1(0) 0(1) * 1(0) 0(1) = 1(00) 0(01) 0(10) 0(11) = 00')
q0q1 = np.kron(q0, q0)
q0q1_vector_00 = q0q1.flatten()
print(q0q1_vector_00)

# Producto tensorial de q0 y q1
print('')
print('Producto tensorial de 1(0) 0(1) * 0(0) 1(1) = 0(00) 1(01) 0(10) 0(11) = 01')
q0q1 = np.kron(q0, q1)
q0q1_vector_01 = q0q1.flatten()
print(q0q1_vector_01)

# Producto tensorial de q1 y q0
print('')
print('Producto tensorial de 0(0) 1(1) * 1(0) 0(1) = 0(00) 0(01) 1(10) 0(11) = 10')
q0q1 = np.kron(q1, q0)
q0q1_vector_10 = q0q1.flatten()
print(q0q1_vector_10)


# Producto tensorial de q1 y q1
print('')
print('Producto tensorial de 0(0) 1(1) * 0(0) 1(1) = 0(00) 0(01) 0(10) 1(11) = 11')
q0q1 = np.kron(q1, q1)
q0q1_vector_11 = q0q1.flatten()
print(q0q1_vector_11)

# Producto tensorial de q0 (Hadamar) y q0
print('')
print('Producto tensorial de 1/2(0) raiz(3)/2(1) * 1(0) 0(1) = 1/2(00) 0(01) raiz(3)/2(10) 0(11)')
q0h = np.dot(h, q0)
q0q1 = np.kron(q0h, q0)
q0q1_vector_h0 = q0q1.flatten()
print(q0q1_vector_h0)

# Producto tensorial de q0 (Hadamar) y q1
print('')
print('Producto tensorial de 1/2(0) raiz(3)/2(1) * 0(0) 1(1) = 0(00) 1/2(01) 0(10) raiz(3)/2(11)')
q0h = np.dot(h, q0)
q0q1 = np.kron(q0h, q1)
q0q1_vector_h1 = q0q1.flatten()
print(q0q1_vector_h1)



Qbit 0 con estado 0 = 1(0) 0(1)
[[1]
 [0]]

Qbit 1 con estado 1 = 0(0) 1(0)
[[0]
 [1]]


Producto tensorial de 1(0) 0(1) * 1(0) 0(1) = 1(00) 0(01) 0(10) 0(11) = 00
[1 0 0 0]

Producto tensorial de 1(0) 0(1) * 0(0) 1(1) = 0(00) 1(01) 0(10) 0(11) = 01
[0 1 0 0]

Producto tensorial de 0(0) 1(1) * 1(0) 0(1) = 0(00) 0(01) 1(10) 0(11) = 10
[0 0 1 0]

Producto tensorial de 0(0) 1(1) * 0(0) 1(1) = 0(00) 0(01) 0(10) 1(11) = 11
[0 0 0 1]

Producto tensorial de 1/2(0) raiz(3)/2(1) * 1(0) 0(1) = 1/2(00) 0(01) raiz(3)/2(10) 0(11)
[0.70710678 0.         0.70710678 0.        ]

Producto tensorial de 1/2(0) raiz(3)/2(1) * 0(0) 1(1) = 0(00) 1/2(01) 0(10) raiz(3)/2(11)
[0.         0.70710678 0.         0.70710678]


In [140]:
resultado_swap_00 = np.dot(swap, q0q1_vector_00)
resultado_swap_01 = np.dot(swap, q0q1_vector_01)
resultado_swap_10 = np.dot(swap, q0q1_vector_10)
resultado_swap_11 = np.dot(swap, q0q1_vector_11)

print('Estado 00 * SWAP = 00')
print(resultado_swap_00)
print('')
print('Estado 01 * SWAP = 10')
print(resultado_swap_01)
print('')
print('Estado 10 * SWAP = 01')
print(resultado_swap_10)
print('')
print('Estado 11 * SWAP = 11')
print(resultado_swap_11)

Estado 00 * SWAP = 00
[1 0 0 0]

Estado 01 * SWAP = 10
[0 0 1 0]

Estado 10 * SWAP = 01
[0 1 0 0]

Estado 11 * SWAP = 11
[0 0 0 1]


In [147]:
estado_entrada_1 = np.array([[1/np.sqrt(2)],
                             [1/np.sqrt(2)]]) 
print('Qbit 1 en superposicion')
print(estado_entrada_1)
print('')
print('Qbit 2 en estado 0')
estado_entrada_2 = q0
print(estado_entrada_2)

print('')
print('Estados de entrada de los 2 qbits')
estado_entrada_total = np.kron( estado_entrada_1, estado_entrada_2)
print(estado_entrada_total)

print('')
print('Aplico una puerta Swap')
estado_final = np.dot(swap, estado_entrada_total)
print(estado_final)

Qbit 1 en superposicion
[[0.70710678]
 [0.70710678]]

Qbit 2 en estado 0
[[1]
 [0]]

Estados de entrada de los 2 qbits
[[0.70710678]
 [0.        ]
 [0.70710678]
 [0.        ]]

Aplico una puerta Swap
[[0.70710678]
 [0.70710678]
 [0.        ]
 [0.        ]]


In [148]:
estado_entrada_1 = np.array([[1/2],
                             [np.sqrt(3)/2]]) 
print('Qbit 1 en superposicion')
print(estado_entrada_1)
print('')
print('Qbit 2 en estado 1')
estado_entrada_2 = q1
print(estado_entrada_2)

print('')
print('Estados de entrada de los 2 qbits')
estado_entrada_total = np.kron( estado_entrada_1, estado_entrada_2)
print(estado_entrada_total)

print('')
print('Aplico una puerta Swap')
estado_final = np.dot(swap, estado_entrada_total)
print(estado_final)

Qbit 1 en superposicion
[[0.5      ]
 [0.8660254]]

Qbit 2 en estado 1
[[0]
 [1]]

Estados de entrada de los 2 qbits
[[0.       ]
 [0.5      ]
 [0.       ]
 [0.8660254]]

Aplico una puerta Swap
[[0.       ]
 [0.       ]
 [0.5      ]
 [0.8660254]]


In [156]:
estado_entrada_1 = q1
print('Qbit 1 en estado 1')
print(estado_entrada_1)
print('')
estado_entrada_2 = q0
print('Qbit 2 en estado 0')
print(estado_entrada_2)

print('')
print('Producto tensorial de 0(0)1(1) * 1(0)0(1) = 0(00) 0(01) 1(10) 0(11) = 10')
estado_entrada_total = np.kron( estado_entrada_1, estado_entrada_2)
print(estado_entrada_total)

print('')
print('Aplico una puerta CNOT = 0(00) 0(01) 0(10) 1(11) = 11')
estado_final = np.dot(cnot, estado_entrada_total)
print(estado_final)

Qbit 1 en estado 1
[[0]
 [1]]

Qbit 2 en estado 0
[[1]
 [0]]

Producto tensorial de 0(0)1(1) * 1(0)0(1) = 0(00) 0(01) 1(10) 0(11) = 10
[[0]
 [0]
 [1]
 [0]]

Aplico una puerta CNOT = 0(00) 0(01) 0(10) 1(11) = 11
[[0]
 [0]
 [0]
 [1]]


In [159]:
# CNOT
resultado_cnot_00 = np.dot(cnot, q0q1_vector_00)
resultado_cnot_01 = np.dot(cnot, q0q1_vector_01)
resultado_cnot_10 = np.dot(cnot, q0q1_vector_10)
resultado_cnot_11 = np.dot(cnot, q0q1_vector_11)

print('Estado 00 * CNOT = 00')
print(resultado_cnot_00)
print('')
print('Estado 01 * CNOT = 01')
print(resultado_cnot_01)
print('')
print('Estado 10 * CNOT = 11')
print(resultado_cnot_10)
print('')
print('Estado 11 * CNOT = 10')
print(resultado_cnot_11)

Estado 00 * CNOT = 00
[1 0 0 0]

Estado 01 * CNOT = 01
[0 1 0 0]

Estado 10 * CNOT = 11
[0 0 0 1]

Estado 11 * CNOT = 10
[0 0 1 0]


In [162]:
# CNOT CON SUPERPOSICION
estado_entrada_1 = np.array([[1/np.sqrt(2)],
                             [1/np.sqrt(2)]]) 
print('Qbit 1 en superposicion')
print(estado_entrada_1)
print('')
print('Qbit 2 en estado 0')
estado_entrada_2 = q0
print(estado_entrada_2)

print('')
print('Estados de entrada de los 2 qbits')
estado_entrada_total = np.kron( estado_entrada_1, estado_entrada_2)
print(estado_entrada_total)

print('')
print('Aplico una puerta CNOT')
estado_final = np.dot(cnot, estado_entrada_total)
print(estado_final)

Qbit 1 en superposicion
[[0.70710678]
 [0.70710678]]

Qbit 2 en estado 0
[[1]
 [0]]

Estados de entrada de los 2 qbits
[[0.70710678]
 [0.        ]
 [0.70710678]
 [0.        ]]

Aplico una puerta CNOT
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]


In [163]:
estado_entrada_1 = np.array([[1/2],
                             [np.sqrt(3)/2]]) 
print('Qbit 1 en superposicion')
print(estado_entrada_1)
print('')
print('Qbit 2 en estado 1')
estado_entrada_2 = q1
print(estado_entrada_2)

print('')
print('Estados de entrada de los 2 qbits')
estado_entrada_total = np.kron( estado_entrada_1, estado_entrada_2)
print(estado_entrada_total)

print('')
print('Aplico una puerta CNOT')
estado_final = np.dot(cnot, estado_entrada_total)
print(estado_final)

Qbit 1 en superposicion
[[0.5      ]
 [0.8660254]]

Qbit 2 en estado 1
[[0]
 [1]]

Estados de entrada de los 2 qbits
[[0.       ]
 [0.5      ]
 [0.       ]
 [0.8660254]]

Aplico una puerta CNOT
[[0.       ]
 [0.5      ]
 [0.8660254]
 [0.       ]]


In [105]:
# Entanglement q0(Hadamar) y q0

q0_1 = np.dot(h, q0)
print('q0 = Compuerta Hadamar')
print(q0_1)

q0_2 = q0
print('q1 = Estado 0')
print(q0_2)


q3 = np.kron( q0_1, q0_2)
print('q3 = Resultado de los estados separados')
print(q3)


q4 = np.dot(cnot, q3)
print('q4 = Se aplica puerta CNOT')
print(q4)

q0 = Compuerta Hadamar
[[0.70710678]
 [0.70710678]]
q1 = Estado 0
[[1]
 [0]]
q3 = Resultado de los estados separados
[[0.70710678]
 [0.        ]
 [0.70710678]
 [0.        ]]
q4 = Se aplica puerta CNOT
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]


In [106]:
# Entanglement q0(Hadamar) y q1

q0_1 = np.dot(h, q0)
print('q0 = Compuerta Hadamar')
print(q0_1)

q0_2 = q1
print('q1 = Estado 1')
print(q0_2)


q3 = np.kron( q0_1, q0_2)
print('q3 = Resultado de los estados separados')
print(q3)


q4 = np.dot(cnot, q3)
print('q4 = Se aplica puerta CNOT')
print(q4)

q0 = Compuerta Hadamar
[[0.70710678]
 [0.70710678]]
q1 = Estado 1
[[0]
 [1]]
q3 = Resultado de los estados separados
[[0.        ]
 [0.70710678]
 [0.        ]
 [0.70710678]]
q4 = Se aplica puerta CNOT
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]


In [107]:
# Entanglement q1(Hadamar) y q0

q0_1 = np.dot(h, q1)
print('q0 = Compuerta Hadamar')
print(q0_1)

q0_2 = q0
print('q1 = Estado 0')
print(q0_2)


q3 = np.kron( q0_1, q0_2)
print('q3 = Resultado de los estados separados')
print(q3)


q4 = np.dot(cnot, q3)
print('q4 = Se aplica puerta CNOT')
print(q4)

q0 = Compuerta Hadamar
[[ 0.70710678]
 [-0.70710678]]
q1 = Estado 0
[[1]
 [0]]
q3 = Resultado de los estados separados
[[ 0.70710678]
 [ 0.        ]
 [-0.70710678]
 [-0.        ]]
q4 = Se aplica puerta CNOT
[[ 0.70710678]
 [ 0.        ]
 [ 0.        ]
 [-0.70710678]]


In [108]:
# Entanglement q1(Hadamar) y q1

q0_1 = np.dot(h, q1)
print('q0 = Compuerta Hadamar')
print(q0_1)

q0_2 = q1
print('q1 = Estado 1')
print(q0_2)


q3 = np.kron( q0_1, q0_2)
print('q3 = Resultado de los estados separados')
print(q3)


q4 = np.dot(cnot, q3)
print('q4 = Se aplica puerta CNOT')
print(q4)

q0 = Compuerta Hadamar
[[ 0.70710678]
 [-0.70710678]]
q1 = Estado 1
[[0]
 [1]]
q3 = Resultado de los estados separados
[[ 0.        ]
 [ 0.70710678]
 [-0.        ]
 [-0.70710678]]
q4 = Se aplica puerta CNOT
[[ 0.        ]
 [ 0.70710678]
 [-0.70710678]
 [ 0.        ]]


# Matriz Input y Output

In [184]:
# INPUT  0 0 0 
# OUTPUT 0 0 0

entrada_1 = q0
print('')
print('Entrada 1 en estado 0')
print(entrada_1)

entrada_2 = q0
print('')
print('Entrada 2 en estado 0')
print(entrada_2)

estado_entrada_1_2 = np.kron(entrada_1, entrada_2)

entrada_3 = q0
print('')
print('Entrada 3 en estado 0')
print(entrada_3)

print('')
print('Estados de entrada de los 3 qbits -> Input(000) Output(000)')
print('')
print('1(000) 0(001) 0(010) 0(011) 0(100) 0(101) 0(110) 0(111)')
print('')
estado_entrada_total = np.kron(estado_entrada_1_2, entrada_3)
estado_entrada_total_vector = estado_entrada_total.flatten()
print(estado_entrada_total_vector)


Entrada 1 en estado 0
[[1]
 [0]]

Entrada 2 en estado 0
[[1]
 [0]]

Entrada 3 en estado 0
[[1]
 [0]]

Estados de entrada de los 3 qbits -> Input(000) Output(000)

1(000) 0(001) 0(010) 0(011) 0(100) 0(101) 0(110) 0(111)

[1 0 0 0 0 0 0 0]
